name: (scheduled) download statistics
env:
  github_token: ${{ secrets.PAT }}
  CUR_REPO: ${{ github.repository }}
on: 
  schedule: 
    - cron: '00 * * * *' 
    # runs every hour
    # minute(0-59) / hour(0-23) / day of month(1-31) / month(1-12) / day of week(0-6)
jobs:
  First:
    name: gather statistics
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: install libs
        run: |
          python3 -m pip install Pillow
      - name: write statistics
        env:
          github_token: ${{ secrets.PAT }}
        run: python res/src/download_statistics.py
      - name: Commit file
        run: |
          git config user.name "script" 
          git config user.email "<>"
          git add .
          git commit -m "dl log written" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          force: true
      - name: write statistics
        run: python res/src/make_readme.py
      - name: Commit file
        run: |
          git config user.name "script" 
          git config user.email "<>"
          git add .
          git commit -m "dl log written" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          force: true
